version: '3'
services:
  geotrouvethon:
    image: reachhubcorp/geotrouvethon:latest
    container_name: geotrouvethon
    build:
      context: ./context/
    ports:
    - "9966:9966"
    networks:
    - reach
networks:
  reach:
