version: '3'
services:
  geotrouvethon:
    image: reachhubcorp/geotrouvethon:latest
    container_name: geotrouvethon
    build:
      context: ./context/
     ports:
        - "9966:9966"
     environment:
        GEOTROUVETHON_PORT: 9966
        GEOTROUVETHON_URL: 0.0.0.0

